variables:
  PROJECT_NAME: ckb-vshn-net
  SEARCH_IMAGE: registry.appuio.ch/search-engine/search-engine:latest

stages:
  - build
  - deploy

.build-docker:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  tags:
    - dockerbuild
  script:
    - docker login -u gitlab-ci -p ${APPUIO_REGISTRY_TOKEN} registry.appuio.ch
    - docker pull $SEARCH_IMAGE || true
    - docker build --cache-from $SEARCH_IMAGE -t $SEARCH_IMAGE .
    - docker push $SEARCH_IMAGE
    # - if [ ${CI_COMMIT_REF_NAME} == "master" ]; then docker push $SEARCH_IMAGE; fi

develop:build:
  extends: .build-docker
  except:
    - master

master:build:
  extends: .build-docker
  only:
    - master
